[build]
  command = "pip install -r requirements.txt"
  publish = "."

[dev]
  command = "python run.py"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200

[functions]
  directory = "netlify/functions"
